### ISSUE TITLE
Add aria-haspopup=dialog to control which opens the modal

### ISSUE THREAD

**Issue by weboverhauls** [svinkle/launchy#11]
Reference:
https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

**Comment by svinkle** [comment]
@weboverhauls After adding `aria-haspopup="dialog"` and testing this change, there doesn't seem to be any announcement of a popup? For example, Safari+VO with `aria-haspopup="true"` there is some sort of announcement, _"popup link"_.  

Should this be set to `true` instead of `dialog` so that screen reader users are aware of this status? Seems like there's no point to setting the value to `dialog` if there's no support for this value. 🤔

**Comment by weboverhauls** [comment]
Correct, full support isn't quite there. Works as the same as aria-haspopup="true" in JAWS and NVDA; announces "menu/submenu". It's up to you if you want to keep it for future-proofing, maybe make it an option, or remove. Won't hurt my feelings on this one :-)

**Comment by svinkle** [comment]
@weboverhauls thanks for the explanation! I kind of figured it was a "future proof" type of thing. My only concern would be for people using it _now_ and not understanding the context. I'll have a think on switching it to `true` for "present" proofing.

Apologies for any hurt feelings elsewhere! That's not at all my intent. I like to have a good conversion about these things, especially when each party brings something interesting and unique to the table. It's such a great opportunity to learn from others in the industry. 🙂
