### ISSUE TITLE
Feature: Allow for custom close controls

### ISSUE THREAD

**Issue by svinkle** [svinkle/launchy#6]
Expose the method to close the window from a custom control. Thinking if someone wasn't to implement something like a `Cancel` or `Ok` buttons in the window.

**Comment by svinkle** [comment]
Reaching out to @kentcdodds for assistance.

Kent, if you have a few minutes, I'd really appreciate a read of this thread and any tips you might have. 🙂

## Backstory

Launchy is an accessible modal window generator. Its use is very simple; wrap your HTML content you want as a modal window with a `<div data-launchy />` element and you're done. The `launchy.js` script dynamically generates all the required elements with appropriate attributes for you.

## The problem

If someone wants to add a custom control, such as an "OK" or "Cancel" button to close the window, this is currently not possible. There is no method exposed to the global scope that controls existing/visible Launchy windows. I see this as major adoption blocker.

## Potential solution?

Expose some sort of `closeAll()` method to the global scope. With this in place, someone could create a custom event listener function, part of which would be a call to the exposed method to close a visible Launchy window.

A very high-level example might be something like:
```html
<button onclick="Launchy.closeAll()">Cancel</button>
```

## What I'm looking for

I can't quite figure out how to create such a global scoped method? As seen on the [Launchy demo page](https://svinkle.github.io/launchy/), you can reach the `modalHide()` method via  `Launchy.Launchy.prototype` but there's some `this` messiness happening.

Kent, are there any tips or resources you could share so I could learn about how to accomplish this? This is possible, right? 🤔

Thank you very much for reading! 🙂🍻

**Comment by kentcdodds** [comment]
Hey friend! My time is a bit [limited](http://kcd.im/no-time), but if I were to build have a modal, I would want the API to be similar to the downshift API. The library would be responsible for logic/state and I would be responsible for rendering and interaction. So something like:

```javascript
<Launchy>
  {({close, /* other state and helpers */}) => (
    <div>
      Hello world! <button onClick={close}>close</button>
    </div>
  )}
</Launchy>
```

From there, you can build any kind of API on top of it. That's where I'd stop personally. I don't need a frameworkless modal implementation.

However, if you do need a frameworkless modal implementation, you could include preact and it'd still be pretty small, and it'd work with any other framework (like Launchy does now). Then you could expose an API like this:

```javascript
launchy.open(({close}) => {
  const rootNode = document.createElement('div')
  rootNode.innerHTML = `
    Hello world! <button>close</button>
  `
  rootNode.getElementsByTagName('button')[0].addEventListener('click', close)
  return rootNode
})
```

Doing it this allows people to do things however they like. So the `open` function is passed state and helpers and what is returned is a DOM node to render. Luckily for you, this should only be called once when the modal is opened. downshift couldn't really do something like this very well because that function would be called many times which would result in devs having to manage focus state among other things.

In any case, having some global somewhere does not seem advisable. Good luck!!
