### ISSUE TITLE
Open/close controls should be buttons

### ISSUE THREAD

**Issue by weboverhauls** [svinkle/launchy#9]
The controls which open and close the modal should be buttons not links.

W3C WAI example:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

**Comment by svinkle** [comment]
I was hoping to avoid this discussion but I guess it's inevitable. 🙂

Yes, the WAI example uses a `button` element for its controls, but from a usability perspective, this doesn't make sense.

Using `a` elements in the context of a dialog window makes sense in that, as web and content authors, we're shifting keyboard focus from one element to another. It can be thought of in the same context as a jump link; jumping from one area of the current page to another area.

With the semantics of a link understood, the user has the knowledge and confidence that, on click, this thing will bring me to a new page, or a new section of the current page.

We should encourage folks to reserve `button`s for things like submitting forms, making on-screen adjustments to data sets (ex., sorting a table column), or some other action that results in a temporary on-screen notice via floating label/`aria-live` element where focus remains stationary on the current element on click.

**Comment by weboverhauls** [comment]
I believe it's common knowledge amongst accessibility experts that button should be used. Nearly all model demos by accessibility experts use button.

**Comment by svinkle** [comment]
Absolutely agree; it is common knowledge and almost all demos out there use `button` elements.

With that said, I'm more interested in creating things that are comfortable for people to use and use with confidence where they don't end up to second-guessing themselves on what will happen on click, as apposed to creating something purely _"technically"_ correct.

**Comment by martynhoyer** [comment]
@svinkle I'm not suggesting that you change it, because I think your argument is valid, but we've been having similar discussions at my organisation around `<button>` vs `<a>` for triggering visibility of things like modals, and I have a couple of scenarios which I'm keen for your thoughts on:

1: The content of the modal is loaded at time of click, i.e. a fetch request is sent and the response used to populate (and perhaps even render) the modal. Using an `<a>` here feels a bit odd if the modal doesn't exist in the DOM until the link is clicked.

2: The user recognises that the element is a link, not a button (maybe because they see the URL in the corner of the browser window on hover) and decides to open it in a new tab. By default they'd be presented with the same page, just with a hash-based anchor in the URL. Would you expect the modal to open if on page load if that URL was shared/refreshed? I believe you'd need some sort of custom JS routing in place to support that?

**Comment by svinkle** [comment]
@martynhoyer These are edge cases I've not considered so these are quite interesting. Thanks for bringing them up.

I've been thinking about this recently actually. I've realized I'm bringing my own bias into the project and essentially forcing this bias upon anyone interested in using the module. I really don't want to do this, so I'm going to be adding a new feature to the API where you can choose which element to use, `a` or `button`. 

I have my reasons, but at the end of the day I'm happy if at least either element is in use. When people implement controls using `div`s and `span`s (which I've seen in production on really big sites) that's when I drop the a11y hammer, lol.

I'll likely being introducing this feature in the coming days, so I'll let you know when this is available.

**Comment by svinkle** [comment]
@martynhoyer Ok, so I just did this now, lol.

Try it out: https://github.com/svinkle/launchy/releases/tag/v0.9.1
